version: '3.1'
services:
  web:
    platform: linux/amd64
    image: odoo:15
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - "./config:/etc/odoo"
      - "./your_project/your-addons:/mnt/extra-addons/your-addons"
      - "./your_project/extra-addons:/mnt/extra-addons/extra-addons"
    command:
      [
        "sh",
        "-c",
        "pip3 install -r /etc/odoo/requirements.txt && python3 -m debugpy --listen 0.0.0.0:5680 /usr/bin/odoo -c /etc/odoo/odoo.conf --dev xml"
      ]
  db:
    image: postgres:15
    container_name: postgres_14_09
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - pg1409:/var/lib/postgresql
      - pg1409_data:/var/lib/postgresql/data

networks:
  default:
    name: my-network
    external: true

volumes:
  pg1409:
  pg1409_data: